runtime: python39

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"
  DATABASE_URL: "sqlite:///documents.db"

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup
