steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/secure-document-sharing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/secure-document-sharing']
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run'
    - 'deploy'
    - 'secure-document-sharing'
    - '--image'
    - 'gcr.io/$PROJECT_ID/secure-document-sharing'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DATABASE_URL=sqlite:///documents.db'

images:
- 'gcr.io/$PROJECT_ID/secure-document-sharing'
